# Generated by Django 4.2.3 on 2023-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_anything', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='code_text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='user_post_image/'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_bg_picture',
            field=models.ImageField(null=True, upload_to='profile_pics/bg'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.ImageField(default='/share_anything/media/profile-img.jpg', upload_to='profile_pics/profile'),
        ),
    ]
