# Generated by Django 4.2.3 on 2023-10-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_anything', '0003_alter_userprofilemodel_profile_bg_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_bg_picture',
            field=models.ImageField(default='default-user-bg.jpg', upload_to='profile_pics/bg'),
        ),
    ]
