# Generated by Django 4.2.3 on 2023-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_anything', '0004_alter_userprofilemodel_profile_bg_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.ImageField(default='profile-img.jpg', upload_to='profile_pics/profile'),
        ),
    ]
