# Generated by Django 4.2.3 on 2023-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_anything', '0006_alter_postmodel_code_text_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='code_text',
            field=models.TextField(blank=True, default='null', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='user_post_image/'),
        ),
    ]
